[package]
name = "disk-verify"
version = "0.1.0"
edition = "2021"
authors = ["bbitmaster@gmail.com"]
description = "High-performance disk testing utility in Rust for validating large drives (10TB+) using pseudorandom patterns"

[dependencies]
libc = "0.2"

